package lists;

import java.util.HashMap;

public class Abilities
{
	public static HashMap<Integer, String> abilities = new HashMap<Integer, String>();

	static
	{
		abilities.put(1, "Stench");
		abilities.put(2, "Drizzle");
		abilities.put(3, "Speed Boost");
		abilities.put(4, "Battle Armor");
		abilities.put(5, "Sturdy");
		abilities.put(6, "Damp");
		abilities.put(7, "Limber");
		abilities.put(8, "Sand Veil");
		abilities.put(9, "Static");
		abilities.put(10, "Volt Absorb");
		abilities.put(11, "Water Absorb");
		abilities.put(12, "Oblivious");
		abilities.put(13, "Cloud Nine");
		abilities.put(14, "Compound Eyes");
		abilities.put(15, "Insomnia");
		abilities.put(16, "Color Change");
		abilities.put(17, "Immunity");
		abilities.put(18, "Flash Fire");
		abilities.put(19, "Shield Dust");
		abilities.put(20, "Own Tempo");
		abilities.put(21, "Suction Cups");
		abilities.put(22, "Intimidate");
		abilities.put(23, "Shadow Tag");
		abilities.put(24, "Rough Skin");
		abilities.put(25, "Wonder Guard");
		abilities.put(26, "Levitate");
		abilities.put(27, "Effect Spore");
		abilities.put(28, "Synchronize");
		abilities.put(29, "Clear Body");
		abilities.put(30, "Natural Cure");
		abilities.put(31, "Lightning Rod");
		abilities.put(32, "Serene Grace");
		abilities.put(33, "Swift Swim");
		abilities.put(34, "Chlorophyll");
		abilities.put(35, "Illuminate");
		abilities.put(36, "Trace");
		abilities.put(37, "Huge Power");
		abilities.put(38, "Poison Point");
		abilities.put(39, "Inner Focus");
		abilities.put(40, "Magma Armor");
		abilities.put(41, "Water Veil");
		abilities.put(42, "Magnet Pull");
		abilities.put(43, "Soundproof");
		abilities.put(44, "Rain Dish");
		abilities.put(45, "Sand Stream");
		abilities.put(46, "Pressure");
		abilities.put(47, "Thick Fat");
		abilities.put(48, "Early Bird");
		abilities.put(49, "Flame Body");
		abilities.put(50, "Run Away");
		abilities.put(51, "Keen Eye");
		abilities.put(52, "Hyper Cutter");
		abilities.put(53, "Pickup");
		abilities.put(54, "Truant");
		abilities.put(55, "Hustle");
		abilities.put(56, "Cute Charm");
		abilities.put(57, "Plus");
		abilities.put(58, "Minus");
		abilities.put(59, "Forecast");
		abilities.put(60, "Sticky Hold");
		abilities.put(61, "Shed Skin");
		abilities.put(62, "Guts");
		abilities.put(63, "Marvel Scale");
		abilities.put(64, "Liquid Ooze");
		abilities.put(65, "Overgrow");
		abilities.put(66, "Blaze");
		abilities.put(67, "Torrent");
		abilities.put(68, "Swarm");
		abilities.put(69, "Rock Head");
		abilities.put(70, "Drought");
		abilities.put(71, "Arena Trap");
		abilities.put(72, "Vital Spirit");
		abilities.put(73, "White Smoke");
		abilities.put(74, "Pure Power");
		abilities.put(75, "Shell Armor");
		abilities.put(76, "Cacophony");
		abilities.put(77, "Air Lock");

		// Gen IV abilities
		abilities.put(78, "Tangled Feet");
		abilities.put(79, "Motor Drive");
		abilities.put(80, "Rivalry");
		abilities.put(81, "Steadfast");
		abilities.put(82, "Snow Cloak");
		abilities.put(83, "Gluttony");
		abilities.put(84, "Anger Point");
		abilities.put(85, "Unburden");
		abilities.put(86, "Heatproof");
		abilities.put(87, "Simple");
		abilities.put(88, "Dry Skin");
		abilities.put(89, "Download");
		abilities.put(90, "Iron Fist");
		abilities.put(91, "Poison Heal");
		abilities.put(92, "Adaptability");
		abilities.put(93, "Skill Link");
		abilities.put(94, "Hydration");
		abilities.put(95, "Solar Power");
		abilities.put(96, "Quick Feet");
		abilities.put(97, "Normalize");
		abilities.put(98, "Sniper");
		abilities.put(99, "Magic Guard");
		abilities.put(100, "No Guard");
		abilities.put(101, "Stall");
		abilities.put(102, "Technician");
		abilities.put(103, "Leaf Guard");
		abilities.put(104, "Klutz");
		abilities.put(105, "Mold Breaker");
		abilities.put(106, "Super Luck");
		abilities.put(107, "Aftermath");
		abilities.put(108, "Anticipation");
		abilities.put(109, "Forewarn");
		abilities.put(110, "Unaware");
		abilities.put(111, "Tinted Lens");
		abilities.put(112, "Filter");
		abilities.put(113, "Slow Start");
		abilities.put(114, "Scrappy");
		abilities.put(115, "Storm Drain");
		abilities.put(116, "Ice Body");
		abilities.put(117, "Solid Rock");
		abilities.put(118, "Snow Warning");
		abilities.put(119, "Honey Gather");
		abilities.put(120, "Frisk");
		abilities.put(121, "Reckless");
		abilities.put(122, "Multitype");
		abilities.put(123, "Flower Gift");
		abilities.put(124, "Bad Dreams");

		// Gen V abilities
		abilities.put(125, "Pickpocket");
		abilities.put(126, "Sheer Force");
		abilities.put(127, "Contrary");
		abilities.put(128, "Unnerve");
		abilities.put(129, "Defiant");
		abilities.put(130, "Defeatist");
		abilities.put(131, "Cursed Body");
		abilities.put(132, "Healer");
		abilities.put(133, "Friend Guard");
		abilities.put(134, "Weak Armor");
		abilities.put(135, "Heavy Metal");
		abilities.put(136, "Light Metal");
		abilities.put(137, "Multiscale");
		abilities.put(138, "Toxic Boost");
		abilities.put(139, "Flare Boost");
		abilities.put(140, "Harvest");
		abilities.put(141, "Telepathy");
		abilities.put(142, "Moody");
		abilities.put(143, "Overcoat");
		abilities.put(144, "Poison Touch");
		abilities.put(145, "Regenerator");
		abilities.put(146, "Big Pecks");
		abilities.put(147, "Sand Rush");
		abilities.put(148, "Wonder Skin");
		abilities.put(149, "Analytic");
		abilities.put(150, "Illusion");
		abilities.put(151, "Imposter");
		abilities.put(152, "Infiltrator");
		abilities.put(153, "Mummy");
		abilities.put(154, "Moxie");
		abilities.put(155, "Justified");
		abilities.put(156, "Rattled");
		abilities.put(157, "Magic Bounce");
		abilities.put(158, "Sap Sipper");
		abilities.put(159, "Prankster");
		abilities.put(160, "Sand Force");
		abilities.put(161, "Iron Barbs");
		abilities.put(162, "Zen Mode");
		abilities.put(163, "Victory Star");
		abilities.put(164, "Turboblaze");
		abilities.put(165, "Teravolt");

		// Gen VI abilities
		abilities.put(166, "Aroma Veil");
		abilities.put(167, "Flower Veil");
		abilities.put(168, "Cheek Pouch");
		abilities.put(169, "Protean");
		abilities.put(170, "Fur Coat");
		abilities.put(171, "Magician");
		abilities.put(172, "Bulletproof");
		abilities.put(173, "Competitive");
		abilities.put(174, "Strong Jaw");
		abilities.put(175, "Refrigerate");
		abilities.put(176, "Sweet Veil");
		abilities.put(177, "Stance Change");
		abilities.put(178, "Gale Wings");
		abilities.put(179, "Mega Launcher");
		abilities.put(180, "Grass Pelt");
		abilities.put(181, "Symbiosis");
		abilities.put(182, "Tough Claws");
		abilities.put(183, "Pixilate");
		abilities.put(184, "Gooey");
		abilities.put(185, "Aerilate");
		abilities.put(186, "Parental Bond");
		abilities.put(187, "Dark Aura");
		abilities.put(188, "Fairy Aura");
		abilities.put(189, "Aura Break");
		abilities.put(190, "Primordial Sea");
		abilities.put(191, "Desolate Land");
		abilities.put(192, "Delta Stream");

		// Gen VII abilities
		abilities.put(193, "Stamina");
		abilities.put(194, "Wimp Out");
		abilities.put(195, "Emergency Exit");
		abilities.put(196, "Water Compaction");
		abilities.put(197, "Merciless");
		abilities.put(198, "Shields Down");
		abilities.put(199, "Stakeout");
		abilities.put(200, "Water Bubble");
		abilities.put(201, "Steelworker");
		abilities.put(202, "Berserk");
		abilities.put(203, "Slush Rush");
		abilities.put(204, "Long Reach");
		abilities.put(205, "Liquid Voice");
		abilities.put(206, "Triage");
		abilities.put(207, "Galvanize");
		abilities.put(208, "Surge Surfer");
		abilities.put(209, "Schooling");
		abilities.put(210, "Disguise");
		abilities.put(211, "Battle Bond");
		abilities.put(212, "Power Construct");
		abilities.put(213, "Corrosion");
		abilities.put(214, "Comatose");
		abilities.put(215, "Queenly Majesty");
		abilities.put(216, "Innards Out");
		abilities.put(217, "Dancer");
		abilities.put(218, "Battery");
		abilities.put(219, "Fluffy");
		abilities.put(220, "Dazzling");
		abilities.put(221, "Soul-Heart");
		abilities.put(222, "Tangling Hair");
		abilities.put(223, "Receiver");
		abilities.put(224, "Power of Alchemy");
		abilities.put(225, "Beast Boost");
		abilities.put(226, "RKS System");
		abilities.put(227, "Electric Surge");
		abilities.put(228, "Psychic Surge");
		abilities.put(229, "Misty Surge");
		abilities.put(230, "Grassy Surge");

		// Gen VIII abilities
		abilities.put(231, "Innards Out");
		abilities.put(232, "Propeller Tail");
		abilities.put(233, "Libero");
		abilities.put(234, "Ball Fetch");
		abilities.put(235, "Cotton Down");
		abilities.put(236, "Mirror Armor");
		abilities.put(237, "Gulp Missile");
		abilities.put(238, "Stalwart");
		abilities.put(239, "Steam Engine");
		abilities.put(240, "Punk Rock");
		abilities.put(241, "Sand Spit");
		abilities.put(242, "Ice Scales");
		abilities.put(243, "Ripen");
		abilities.put(244, "Ice Face");
		abilities.put(245, "Power Spot");
		abilities.put(246, "Mimicry");
		abilities.put(247, "Screen Cleaner");
		abilities.put(248, "Perish Body");
		abilities.put(249, "Wandering Spirit");
		abilities.put(250, "Gorilla Tactics");
		abilities.put(251, "Neutralizing Gas");
		abilities.put(252, "Pastel Veil");
		abilities.put(253, "Hunger Switch");
		abilities.put(254, "Quick Draw");
		abilities.put(255, "Unseen Fist");
		abilities.put(256, "Curious Medicine");
		abilities.put(257, "Transistor");
		abilities.put(258, "Dragon's Maw");
		abilities.put(259, "Chilling Neigh");
		abilities.put(260, "Grim Neigh");
		abilities.put(261, "As One");

		// Gen IX abilities
		abilities.put(262, "Lingering Aroma");
		abilities.put(263, "Seed Sower");
		abilities.put(264, "Thermal Exchange");
		abilities.put(265, "Anger Shell");
		abilities.put(266, "Purifying Salt");
		abilities.put(267, "Well-Baked Body");
		abilities.put(268, "Wind Rider");
		abilities.put(269, "Guard Dog");
		abilities.put(270, "Rocky Payload");
		abilities.put(271, "Wind Power");
		abilities.put(272, "Zero to Hero");
		abilities.put(273, "Commander");
		abilities.put(274, "Electromorphosis");
		abilities.put(275, "Protosynthesis");
		abilities.put(276, "Quark Drive");
		abilities.put(277, "Good as Gold");
		abilities.put(278, "Vessel of Ruin");
		abilities.put(279, "Sword of Ruin");
		abilities.put(280, "Tablets of Ruin");
		abilities.put(281, "Beads of Ruin");
		abilities.put(282, "Orichalcum Pulse");
		abilities.put(283, "Hadron Engine");
		abilities.put(284, "Opportunist");
		abilities.put(285, "Cud Chew");
		abilities.put(286, "Sharpness");
		abilities.put(287, "Supreme Overlord");
		abilities.put(288, "Costar");
		abilities.put(289, "Toxic Debris");
		abilities.put(290, "Armor Tail");
		abilities.put(291, "Earth Eater");
		abilities.put(292, "Mycelium Might");
		// Continue adding new abilities as they are released in future games
	}
}
